#!/usr/bin/env python3
"""
Шаг 3 пайплайна: рендер готового markdown-текста issue по провалидированному JSON.
Чистый код, никакого LLM — форма ответа целиком детерминирована шаблоном.

Использование:
    python3 render-issue.py <provider> < issue.json > issue.md
    python3 render-issue.py github --json issue.json --out issue.md

provider: github | gitlab | gitea | bitbucket
"""
import argparse
import json
import sys
from pathlib import Path

CHECKBOX_PROVIDERS = {"github", "gitlab", "gitea"}  # markdown-чекбоксы поддерживаются
BITBUCKET_DASH = "-"  # Bitbucket Cloud тоже понимает обычный markdown


def render(data: dict, provider: str) -> str:
    parts = []

    kind = data["type"]
    kind_label = {"bug": "🐛 Bug", "feature": "✨ Feature", "task": "📋 Task"}[kind]
    parts.append(f"## {kind_label}\n")

    parts.append("### Description\n")
    parts.append(data["description"].strip() + "\n")

    if data.get("steps_to_reproduce"):
        parts.append("### Steps to Reproduce\n")
        bullet = "- [ ]" if provider in CHECKBOX_PROVIDERS else BITBUCKET_DASH
        for i, step in enumerate(data["steps_to_reproduce"], 1):
            parts.append(f"{bullet} {i}. {step}")
        parts.append("")

    if data.get("expected"):
        parts.append("### Expected Behavior\n")
        parts.append(data["expected"].strip() + "\n")

    if data.get("actual"):
        parts.append("### Actual Behavior\n")
        parts.append(data["actual"].strip() + "\n")

    if data.get("environment"):
        parts.append("### Environment\n")
        parts.append(data["environment"].strip() + "\n")

    # GitLab quick actions — только для gitlab, и только если есть labels
    if provider == "gitlab" and data.get("labels"):
        parts.append("/label " + " ".join(f"~{l}" for l in data["labels"]))
        parts.append(f"/priority {data.get('priority', 'medium')}\n")

    parts.append("---")
    parts.append(f"*priority: {data.get('priority', 'medium')} · generated by issue-writer agent*")

    return "\n".join(parts).strip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("provider", choices=["github", "gitlab", "gitea", "bitbucket"])
    ap.add_argument("--json", dest="json_path", default=None, help="путь к issue.json (иначе — stdin)")
    ap.add_argument("--out", dest="out_path", default=None, help="куда писать markdown (иначе — stdout)")
    args = ap.parse_args()

    text = Path(args.json_path).read_text(encoding="utf-8") if args.json_path else sys.stdin.read()
    data = json.loads(text)

    md = render(data, args.provider)

    if args.out_path:
        Path(args.out_path).write_text(md, encoding="utf-8")
    else:
        sys.stdout.write(md)

    return 0


if __name__ == "__main__":
    sys.exit(main())
