#!/usr/bin/env python3
"""
Рендер стандартизированного текста PR по провалидированному JSON.
Чистый код, никакого LLM — формат целиком детерминирован шаблоном,
агент не пишет body свободной формой.

Использование:
    python3 render-pr.py <provider> --json pr.json --out body.md
    python3 render-pr.py github < pr.json > body.md

provider: github | gitlab | gitea | bitbucket
"""
import argparse
import json
import sys
from pathlib import Path


def render(data: dict, provider: str) -> str:
    parts = []

    parts.append("## Summary\n")
    parts.append(data["summary"].strip() + "\n")

    parts.append("## Changes\n")
    for change in data["changes"]:
        parts.append(f"- {change.strip()}")
    parts.append("")

    parts.append("## How to verify\n")
    for step in data["test_plan"]:
        parts.append(f"- [ ] {step.strip()}")
    parts.append("")

    if data.get("notes"):
        parts.append("## Notes\n")
        parts.append(data["notes"].strip() + "\n")

    # GitLab quick actions — только для gitlab, и только если есть labels
    if provider == "gitlab" and data.get("labels"):
        parts.append("/label " + " ".join(f"~{l}" for l in data["labels"]))
        parts.append("")

    parts.append("---")
    parts.append("*generated by pr pipeline (`scripts/pr/`)*")

    return "\n".join(parts).strip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("provider", choices=["github", "gitlab", "gitea", "bitbucket"])
    ap.add_argument("--json", dest="json_path", default=None, help="путь к pr.json (иначе — stdin)")
    ap.add_argument("--out", dest="out_path", default=None, help="куда писать markdown (иначе — stdout)")
    args = ap.parse_args()

    text = Path(args.json_path).read_text(encoding="utf-8") if args.json_path else sys.stdin.read()
    data = json.loads(text)

    md = render(data, args.provider)

    if args.out_path:
        Path(args.out_path).write_text(md, encoding="utf-8")
    else:
        sys.stdout.write(md)

    return 0


if __name__ == "__main__":
    sys.exit(main())
